version: '3'
services:
  cassandra-1:
    image: cassandra:latest
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_SEEDS: cassandra-1,cassandra-2,cassandra-3
      CASSANDRA_BROADCAST_ADDRESS: cassandra-1
    mem_limit: 6g
    
  cassandra-2:
    image: cassandra:latest
    ports:
      - "9043:9042"
    environment:
      CASSANDRA_SEEDS: cassandra-1,cassandra-2,cassandra-3
      CASSANDRA_BROADCAST_ADDRESS: cassandra-2
    mem_limit: 6g

  cassandra-3:
    image: cassandra:latest
    ports:
      - "9044:9042"
    environment:
      CASSANDRA_SEEDS: cassandra-1,cassandra-2,cassandra-3
      CASSANDRA_BROADCAST_ADDRESS: cassandra-3
    mem_limit: 6g
